### ISSUE TITLE
random starting local server when executing jasmine tests

### ISSUE THREAD

**Issue by BabylonZeus** [searls/jasmine-maven-plugin#250] opened 2014-07-09 15:17 UTC
Using : maven 3.2.2, jasmine-maven-plugin 2.0-alpha-01, jasmine 2.0.0
Environment : cygwin on windows 8.1
Goal : test
webDriver : PhantomJSDriver (Phantom 1.9.7)

The plugin starts a local server on an available port then executes jasmine tests. Randomly, the report shows tests are found and executed ok, sometimes it finds only some tests and fail, and sometimes it finds 0 test (and so build success).
The same "mvn test" executed several times shows this clear random behaviour.

After looking at the source, I found in "SpecRunnerExecutor.execute" a call to "this.waitForRunnerToFinish" : I made the hypothesis that it could not wait properly for the server to start. I put a Thread.sleep(2000) just before that call to check it.
Since then, the tests are found and executed correctly every time. After tens of executions, I never had one failure with this Thread.sleep.

It seems that the "waitForRunnerToFinish" is not executing properly.

**Comment by lkiesow** [comment] 2015-05-06 14:36
I can confirm this issue. I'm seeing the tests randomly failing since [Opencast Matterhorn](https://bitbucket.org/opencast-community/matterhorn) included the jasmine-maven-plugin for its new JS based player.

 - Apache Maven 3.2.2
 -  jasmine-maven-plugin 1.3.1.6, 2-alpha-1, 2-beta-1
 - Java version: 1.8.0_45

**Comment by lkiesow** [comment] 2015-05-07 11:36
As addition to
> The plugin starts a local server on an available port then executes jasmine tests.

If the test fails, there is still a phantomjs process running after Maven exited.

**Comment by klieber** [comment] 2018-10-25 14:18
Closing this ticket since PhantomJS support is being dropped since the project is [no longer in development](ariya/phantomjs#15344).

There is an alpha version of the plugin available that uses headless Chrome available:
https://github.com/searls/jasmine-maven-plugin/releases/tag/jasmine-maven-plugin-3.0-alpha-01

If the issue still exists in that version I can reopen the ticket.

**Closed by klieber** 2018-10-25 14:18 UTC
Labels: bug
